// <auto-generated />
using FormulaOne.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FormulaOne.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FormulaOne.Shared.Models.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RacingNb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Drivers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Michael Schumacher",
                            RacingNb = "3",
                            Team = "Mercedes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Nico Rosberg",
                            RacingNb = "6",
                            Team = "Mercedes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lewis Hamilton",
                            RacingNb = "44",
                            Team = "Mercedes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Valtteri Bottas",
                            RacingNb = "77",
                            Team = "Mercedes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "George Russell",
                            RacingNb = "63",
                            Team = "Mercedes"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Michael Schumacher",
                            RacingNb = "1",
                            Team = "Ferrari"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Felipe Massa",
                            RacingNb = "6",
                            Team = "Ferrari"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Kimi Räikkönen",
                            RacingNb = "7",
                            Team = "Ferrari"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Fernando Alonso",
                            RacingNb = "14",
                            Team = "Ferrari"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Sebastian Vettel",
                            RacingNb = "5",
                            Team = "Ferrari"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Charles Leclerc",
                            RacingNb = "16",
                            Team = "Ferrari"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Carlos Sainz",
                            RacingNb = "55",
                            Team = "Ferrari"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
